-- FaciTurno - Supabase setup
-- Run this once in the Supabase SQL Editor. Creates every table the app
-- needs: workers plus the configuration tables (departments, shifts, rooms,
-- app_settings), all with public RLS access.

-- 1. Workers (Trabajadores)
CREATE TABLE IF NOT EXISTS public.workers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  position TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);
ALTER TABLE public.workers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public full access to workers"
  ON public.workers FOR ALL TO anon USING (true) WITH CHECK (true);

-- 2. Departments (Áreas / Departamentos)
CREATE TABLE IF NOT EXISTS public.departments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public full access to departments"
  ON public.departments FOR ALL TO anon USING (true) WITH CHECK (true);

-- 3. Shifts (Turnos / Horarios)
CREATE TABLE IF NOT EXISTS public.shifts (
  id TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  icon TEXT NOT NULL DEFAULT 'clock-outline',
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);
ALTER TABLE public.shifts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public full access to shifts"
  ON public.shifts FOR ALL TO anon USING (true) WITH CHECK (true);

-- 4. Rooms (Salas)
CREATE TABLE IF NOT EXISTS public.rooms (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  department TEXT NOT NULL,
  staffing_mode TEXT NOT NULL DEFAULT 'total',
  staff_count INTEGER NOT NULL DEFAULT 1,
  positions JSONB NOT NULL DEFAULT '[]',
  status TEXT NOT NULL DEFAULT 'available',
  notes TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);
ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public full access to rooms"
  ON public.rooms FOR ALL TO anon USING (true) WITH CHECK (true);

-- 5. App settings (preferencias del centro hospitalario y tema)
CREATE TABLE IF NOT EXISTS public.app_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public full access to app_settings"
  ON public.app_settings FOR ALL TO anon USING (true) WITH CHECK (true);